CREATE TABLE AUTHOR (
  ID 		    VARCHAR(50) 	NOT NULL,
  NAME 		    VARCHAR(15) 	NOT NULL,
  EMAIL 	    VARCHAR(50) 	NOT NULL
);


CREATE TABLE POST (
  ID 		        VARCHAR(50) 	NOT NULL,
  TITLE 		    VARCHAR(50) 	NOT NULL,
  DESCRIPTION 	    VARCHAR(50) 	NOT NULL,
  CATEGORY 	        VARCHAR(15) 	NOT NULL,
  AUTHOR_ID 	    VARCHAR(50) 	NOT NULL
);

CREATE TABLE COMMENT (
  ID 		        VARCHAR(50) 	NOT NULL,
  TEXT 		        VARCHAR(50) 	NOT NULL,
  AUTHOR_ID 	    VARCHAR(50) 	NOT NULL,
  POST_ID 	        VARCHAR(50) 	NOT NULL
);